services:
    app:
        env_file:
            - ./.env
        build:
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 80:80

    postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        env_file:
            - /home/amorales/env-files/.env.riesgos-backend-prod
        volumes:
            - /home/amorales/apps-volumes/postgres/data:/var/lib/postgresql/data
